# Generated by Django 3.1.3 on 2021-02-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_init', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='main_phone',
            field=models.CharField(max_length=20),
        ),
    ]
